# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-social-image-issue',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/test-social-image-issue',
                'lib_path': 'test_social_image_issue'},
  'syms': {'test_social_image_issue.core': {'test_social_image_issue.core.foo': ('core.html#foo', 'test_social_image_issue/core.py')}}}
