# Site
site_name: test-social-image-issue
site_url: https://harishmohanraj.github.io/test-social-image-issue
site_author: Harish Mohan Raj
site_description: test-social-image-issue

# Repository
repo_name: test-social-image-issue
repo_url: https://github.com/harishmohanraj/test-social-image-issue
edit_uri: ""

copyright: 2023 onwards, Harish Mohan Raj

docs_dir: docs
site_dir: site

plugins:
- literate-nav:
    nav_file: SUMMARY.md
- search
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        options:
          heading_level: 2
          show_category_heading: true
          show_root_heading: true
          show_root_toc_entry: true
          show_signature_annotations: true
          show_if_no_docstring: true

markdown_extensions:
- md_in_html
- pymdownx.arithmatex:
    generic: true
- pymdownx.inlinehilite
- pymdownx.details
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tasklist
- pymdownx.highlight:
    linenums: false
- pymdownx.snippets:
    check_paths: true
- pymdownx.tabbed:
    alternate_style: true
- admonition
- toc:
    permalink: "¤"
#     - callouts
theme:
  name: material
  custom_dir: site_overrides
  features:
  - navigation.instant
#     - navigation.tabs
#     - navigation.tabs.sticky
#     - navigation.sections
#     - navigation.expand
  - navigation.indexes
  - navigation.top
#     - toc.integrates
  - search.suggest
  - search.highlight
  - search.share
  palette:
  - scheme: slate
    primary: black
    accent: yellow
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - scheme: default
    primary: black   # deep orange
    accent: red
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
#     repo: fontawesome/brands/gitlab
    logo: material/compass-outline
#     admonition:
#         <type>: <icon> 
  favicon: overrides/images/compass-outline.png

extra_css:
- overrides/css/extra.css

extra_javascript:
- overrides/js/extra.js
- overrides/js/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  version:
    provider: mike
  social_image: "https://oaidalleapiprodscus.blob.core.windows.net/private/org-LBy7AaclD79jXaMx6Ds3lZ4t/user-IFvs3ttTo9NIqTXESdSS6WL0/img-U3gimDhPDkCVcf9yUGFejqrx.png?st=2023-06-26T07%3A08%3A21Z&se=2023-06-26T09%3A08%3A21Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-06-25T16%3A14%3A58Z&ske=2023-06-26T16%3A14%3A58Z&sks=b&skv=2021-08-06&sig=SNQ4eYkVCtojLWOLwHRIqEFkkMV1IWytkkpeuTDSOAs%3D"
